baseURL = "/"
languageCode = "en-us"
title = "Prashant's Nook"
theme = "PaperMod"
paginate = 4

disqusShortname = ""
googleAnalytics = ""

[author]
name = "Prashant N"

[params]
author = "Prashant N"
description = ""
dateFormat = "2006-01-02"
paginationSinglePost = true
style = "auto"
readMore = true


# utteranc.es support
utterancesRepo = ""  # mandatory
utterancesTheme = "" # optional
utterancesIssue = "" # optional
utterancesLabel = "" # optional

[[params.social]]
id = "linkedin"
url = "https://linkedin.com/user/itspacchu"

[[params.social]]
id = "github"
url = "https://github.com/itspacchu"

env = "production"
description = "Prashant's Nook"
author = "Prashant"
defaultTheme = "auto"
ShowShareButtons = true
ShowReadingTime = true
displayFullLangName = true
ShowPostNavLinks = true
ShowBreadCrumbs = true
ShowCodeCopyButtons = true
ShowToc = false
images = [
  "papermod-cover.png"
]

[params.profileMode]
enabled = true
title = "Prashant's Nook"
subtitle = "Hello fellow earthlings, I see you have stumbled on my website <hr> Here are some places you can go to."
imageUrl = "https://avatars.githubusercontent.com/u/37984032"
imageTitle = "rip internet!"

[[params.profileMode.buttons]]
name = "About"
url = "about/"

[[params.profileMode.buttons]]
name = "Projects"
url = "projects/"

[[params.profileMode.buttons]]
name = "Blog"
url = "post/"

[[params.profileMode.buttons]]
name = "Resume"
url = "/cdn/resume.pdf"

[[params.socialIcons]]
name = "linkedin"
url = "https://in.linkedin.com/in/prashantnook"

[[params.socialIcons]]
name = "github"
url = "https://github.com/itspacchu"

[[params.socialIcons]]
name = "spotify"
url = "https://open.spotify.com/user/pacchuprashant"

[[params.socialIcons]]
name = "instagram"
url = "https://instagram.com/itspacchu"

[[params.socialIcons]]
name = "youtube"
url = "https://www.youtube.com/channel/UCpVLV3pxEJHfUqz6FG199Uw"


[menu]
[[menu.main]]
identifier = "about"
name = "About"
url = "/about/"
weight = 1

[[menu.main]]
identifier = "projects"
name = "Projects"
url = "/projects/"
weight = 2

[[menu.main]]
name = "Posts"
identifier = "posts"
url = "/post/"
weight = 3

[taxonomies]
category = "categories"
tag = "tags"

[markup.goldmark.renderer]
unsafe = true

[outputs]
home = [
  "HTML",
  "RSS",
  "JSON"
]