baseURL: "https://prashantnook.in"
languageCode: "en-us"
title: "Prashant's Nook"
theme: "PaperMod-pacblog"
paginate: 4
disqusShortname: ""
googleAnalytics: ""

author:
  name: "Prashant Nandipati"

params:
  author: "Prashant N"
  paginationSinglePost: true
  style: "auto"
  readMore: true
  utterancesRepo: ""
  utterancesTheme: ""
  utterancesIssue: ""
  utterancesLabel: ""
  social:
    - id: "linkedin"
      url: "https://linkedin.com/user/itspacchu"
    - id: "github"
      url: "https://github.com/itspacchu"
  env: "production"
  description: "Prashant's Nook"
  defaultTheme: "auto"
  disableThemeToggle: true
  ShowShareButtons: false
  ShowReadingTime: true
  displayFullLangName: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowToc: true
  images:
    - "https://github.com/user-attachments/assets/5315feb1-d53b-4f96-b158-fe9f199fd226"
  profileMode:
    enabled: true
    title: "Prashant's Nook"
    subtitle: "Hello fellow earthlings, I see you have stumbled on my website <hr> Here are some places you can go to."
    imageUrl: "https://avatars.githubusercontent.com/u/37984032"
    imageTitle: "rip internet!"
    buttons:
      - name: "About"
        url: "about/"
      - name: "Projects"
        url: "projects/"
      - name: "Posts"
        url: "post/"
      - name: "Résumé"
        url: "https://cdn.prashantnook.in/resume.pdf"
  socialIcons:
    - name: "linkedin"
      url: "https://in.linkedin.com/in/prashantnook"
    - name: "github"
      url: "https://github.com/itspacchu"
    - name: "spotify"
      url: "https://open.spotify.com/user/pacchuprashant"
    - name: "instagram"
      url: "https://instagram.com/itspacchu"
    - name: "youtube"
      url: "https://www.youtube.com/channel/UCpVLV3pxEJHfUqz6FG199Uw"

menu:
  main:
    - identifier: "about"
      name: "About"
      url: "/about/"
      weight: 1
    - identifier: "projects"
      name: "Projects"
      url: "/projects/"
      weight: 2
    - identifier: "posts"
      name: "Posts"
      url: "/post/"
      weight: 3
    - identifier: "vlogs"
      name: "Vlogs"
      url: "/vlogs/"
      weight: 4
    - identifier: "search"
      name: "Search"
      url: "/search/"
      weight: 5

taxonomies:
  category: "categories"
  tag: "tags"

markup:
  goldmark:
    renderer:
      unsafe: true
  highlight:
    noClasses: false
    # anchorLineNos: true
    codeFences: true
    guessSyntax: true
    lineNos: true
    style: monokai

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
