version: '3.9'
services:
    hugo:
      container_name: hugo
      build: .
      command: hugo --destination /export
      volumes:
        - ./build:/export
      environment:
        GIT_URL: https://github.com/itspacchu/pacblog

    web:
      image: nginx
      restart: always
      depends_on: 
        - hugo
      volumes:
      - ./build:/usr/share/nginx/html
      - ~/cdn:/usr/share/nginx/html/cdn
      - ./nginx/default:/etc/nginx/sites-enables/default
      ports:
      - "8086:80"