---
apiVersion: v1
kind: Namespace
metadata:
  name: blog
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: pacblog
    type: blog
  name: pacblog
  namespace: blog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pacblog
  template:
    metadata:
      labels:
        app: pacblog
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - homelab
      containers:
      - image: registry.gitlab.com/itspacchu/pacblog:armv3
        imagePullPolicy: Always
        name: pacblog
        ports:
        - containerPort: 80
        volumeMounts:
        - name: cdn-volume
          mountPath: /usr/share/nginx/html/cdn
      volumes:
      - name: cdn-volume
        hostPath:
          path: /mnt/media/extssd/cdn
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: pacblog-service
  name: pacblog-service
  namespace: blog
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: pacblog
  type: NodePort
status:
  loadBalancer: {}
