on:
  push:
    branches:
      - master

jobs:
  GitlabMirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/itspacchu/pacblog"
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "itspacchu"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "42900035"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  GitLabRegistryPush:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@v1
      - name: Login into docker
        run: docker login -u itspacchu -p ${{ secrets.GITLAB_PASSWORD }} registry.gitlab.com/itspacchu/pacblog
      - name: Build
        run: docker build -t registry.gitlab.com/itspacchu/pacblog:arm${{ github.run_number }} .
      - name: Push image 
        run: docker push registry.gitlab.com/itspacchu/pacblog:arm${{ github.run_number }}
