on:
  push:
    branches:
      - master

jobs:
  UpdateTheme:
    runs-on: self-hosted

    steps:
      - name: Pull Submodule Papermod
        run: cd /home/ubuntu/coding/pacblog && git submodule update --init --recursive

  UpdateServer:
    runs-on: self-hosted

    steps:
      - name: stash local changes before 
        run: cd /home/ubuntu/coding/pacblog && git stash

      - name: pull new changes from github
        run: cd /home/ubuntu/coding/pacblog && git pull origin


  GenerateHtmlFiles:
    runs-on: self-hosted
    needs: UpdateServer UpdateTheme
    steps:
      - name: run the updater script
        run: cd /home/ubuntu/coding/pacblog && hugo

  RestartNginx:
    runs-on: self-hosted
    needs: GenerateHtmlFiles

    steps:
      - name: restart nginx server
        run:  sudo systemctl restart nginx