on:
  push:
    branches:
      - master

jobs:
  GitlabMirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/itspacchu/pacblog"
      env:
        FORCE_PUSH: "true"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "itspacchu"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "42900035"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  
  GitLabRegistryPush:
    needs: [GitlabMirror]
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v1
      - name: Login into docker
        run: podman login -u itspacchu -p ${{ secrets.GITLAB_PASSWORD }} registry.gitlab.com/itspacchu/pacblog
      - name: Build and Push
        run: podman build -t registry.gitlab.com/itspacchu/pacblog:arm${{ github.run_number }} --push .

  RunOnHomePi:
    needs: [GitLabRegistryPush] 
    runs-on: [self-hosted]
    steps:
      - name: Run Kubernetes manifest on selfhosted machine
        run: |
          curl https://raw.githubusercontent.com/itspacchu/pacblog/master/k8s-manifest.yaml | sed "s/latest/arm${{ github.run_number }}/g" | kubectl apply -f -
