on:
  push:
    branches:
      - master

jobs:
  GitlabMirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/itspacchu/pacblog"
      env:
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "svboxel"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "42900035"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  GitLabRegistryPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login into docker
        run: docker login -u $ itspacchu -p ${{ secrets.GITLAB_PASSWORD }} registry.gitlab.com/itspacchu/pacblog
      - name: Build docker
        run: docker build -t registry.gitlab.com/itspacchu/pacblog:arm .
      - name: Push Registry
        run: docker push registry.gitlab.com/itspacchu/pacblog:arm

