on:
  push:
    branches:
      - main

jobs:
  UpdateTheme:
    runs-on: self-hosted

    steps:
      - name: Update theme from papermod
        run: cd /home/ubuntu/coding/pacblog/themes/PaperMod && git pull origin master

  UpdateServer:
    runs-on: self-hosted

    steps:
      - name: stash local changes before 
        run: cd /home/ubuntu/coding/pacblog && git stash

      - name: pull new changes from github
        run: cd /home/ubuntu/coding/pacblog && git pull origin main

  BuildHtml:
    runs-on: self-hosted
      - name: run the updater script
        run: cd /home/ubuntu/coding/pacblog && hugo

  RestartNginx:
    runs-on: self-hosted
      - name: restart nginx server
        run:  sudo systemctl restart nginx