on:
  push:
    branches:
      - master

jobs:
  GitlabMirror:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Mirror + trigger CI
      uses: SvanBoxel/gitlab-mirror-and-ci-action@master
      with:
        args: "https://gitlab.com/itspacchu/pacblog"
      env:
        FORCE_PUSH: "false"
        GITLAB_HOSTNAME: "gitlab.com"
        GITLAB_USERNAME: "itspacchu"
        GITLAB_PASSWORD: ${{ secrets.GITLAB_PASSWORD }}
        GITLAB_PROJECT_ID: "42900035"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  GitLabRegistryPush:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login into docker
        run: docker login -u itspacchu -p ${{ secrets.GITLAB_PASSWORD }} registry.gitlab.com/itspacchu/pacblog:arm
      - name: Build and Push
        env:
          CLOUDFLARED_SECRET: ${{ secrets.CLOUDFLARED_SECRET }}
        run: |
          docker buildx build \
            --platform=linux/arm64 \
            --build-arg CLOUDFLARED_SECRET="${CLOUDFLARED_SECRET}" \
            -t registry.gitlab.com/itspacchu/pacblog:arm \
            --push .

  RunOnHomePi:
    needs: [GitLabRegistryPush] 
    runs-on: [self-hosted, homepi]
    steps:
      - name: Run Uploaded Docker Image
        run: |
          kubectl apply -f ./k8s-manifest.yaml
