on:
  push:
    branches:
      - master

jobs:
  GitLabRegistryPush:
    runs-on: [self-hosted]
    steps:
      - uses: actions/checkout@v1
      - name: Login into docker
        run: docker login -u itspacchu -p ${{ secrets.GITLAB_PASSWORD }} registry.gitlab.com/itspacchu/pacblog
      - name: Build and Push
        run: docker build -t registry.gitlab.com/itspacchu/pacblog:arm${{ github.run_number }} --push .

  RunOnHomePi:
    needs: [GitLabRegistryPush] 
    runs-on: [self-hosted]
    steps:
      - name: Run Kubernetes manifest on selfhosted machine
        run: |
          curl https://raw.githubusercontent.com/itspacchu/pacblog/master/k8s-manifest.yaml | sed "s/latest/arm${{ github.run_number }}/g" | kubectl apply -f -
